name: Python Syntax Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  syntax_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Check Python syntax
        run: |
          python -m compileall .
          if [ $? -ne 0 ]; then
             echo "Syntax errors found!"
             exit 1
          else
             echo "No syntax errors found."
          fi
